import streamlit as st

st.title("Demo Application")
st.write("This is a simple demo application using Streamlit.")
st.button("Click me!", on_click=lambda: st.write("Button clicked!"))
st.checkbox("Check me!", on_change=lambda: st.write("Checkbox checked!"))
st.text_input("Enter some text:", on_change=lambda: st.write("Text input changed!"))
st.slider("Select a value:", min_value=0, max_value=100, on_change=lambda: st.write("Slider value changed!"))   
st.selectbox("Choose an option:", ["Option 1", "Option 2", "Option 3"], on_change=lambda: st.write("Selectbox option changed!"))
st.radio("Pick one:", ["Choice A", "Choice B", "Choice C"], on_change=lambda: st.write("Radio button selection changed!"))
st.text_area("Write something:", on_change=lambda: st.write("Text area content changed!"))
st.date_input("Pick a date:", on_change=lambda: st.write("Date input changed!"))
st.time_input("Pick a time:", on_change=lambda: st.write("Time input changed!"))
st.file_uploader("Upload a file:", on_change=lambda: st.write("File uploaded!"))
st.color_picker("Pick a color:", on_change=lambda: st.write("Color picked!"))
st.progress(70)
st.balloons()
st.snow()
st.success("Success!")
st.error("Error occurred!")
st.warning("Warning message!")